pravega/bookkeeper-operator

README.md, charts/bookkeeper/templates/_helpers.tpl, charts/bookkeeper/templates/bookkeeper.yaml, charts/bookkeeper/templates/config_map.yaml, charts/bookkeeper/values.yaml, deploy/config_map.yaml, deploy/crds/cr.yaml, doc/bookkeeper-options.md, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go, pkg/controller/bookkeepercluster/bookie.go
The Bookkeeper Operator should enable ingestion of environment variables into the Bookie container by allowing users to create a custom config map and specify its same within the Bookkeeper Spec.
Fixes #5 
It allows the user to provide the name of the config map `envVars` within the manifest file, which contains all the user defined environment variables that need to be ingested into the Bookie container.
The key-value pairs that have been added to the config map created by the user should be added to the list of environment variables of the bookkeeper pods.
=> Issue 5: Allowing ingestion of user defined env vars into Bookie containers

README.md, charts/bookkeeper-operator/templates/operator.yaml, charts/bookkeeper-operator/values.yaml, deploy/crds/cr.yaml, doc/manual-installation.md, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go, pkg/controller/config/config.go
To add a `testmode` flag so that user can run operator in test mode if required.
Fixes #18 
Adds a flag `testmode` in values.yaml file, so that user can run operator in test mode if required, which skips the minimum replica requirement checks on bookkeeper instances.
With these changes user will be able to deploy the operator in test mode by changing `deploy/operator.yaml` file during manual installation and by changing `charts/bookkeeper-operator/values.yaml` while installing via charts.
=> Issue 18: Adding TestMode flag in charts

charts/bookkeeper-operator/Chart.yaml, charts/bookkeeper-operator/templates/clusterrole.yaml, charts/bookkeeper-operator/templates/operator.yaml, charts/bookkeeper-operator/values.yaml, charts/bookkeeper/Chart.yaml, deploy/operator.yaml, deploy/role.yaml
The change enables the Bookkeeper Operator to deploy a Bookkeeper Cluster in a different namespace.
Fixes #23 
Sets the `WATCH_NAMESPACE` of the Bookeeper Operator to `""` which enables it to deploy a Bookkeeper Cluster in a different namespace. Also adds the necessary cluster-roles to create this deployment.
Try to deploy a Bookkeeper Cluster in a different namespace `bk` by adding the following within the bookkeeper manifest file
```
metadata:
name: "pravega-bk"
namespace: "bk"
```
The Bookkeeper Cluster will get deployed in the specified namespace
```
$ kubectl get po -A
NAMESPACE     NAME                                        READY   STATUS      RESTARTS   AGE
default       bookkeeper-operator-6f68cb6df-2mstv         1/1     Running …
```
=> Issue 23: Deploying Bookkeeper Cluster in a different namespace

charts/bookkeeper/README.md, charts/bookkeeper/templates/bookkeeper.yaml, charts/bookkeeper/values.yaml
In January 2020 I merged change to support custom storage classes for zookeeper and bookkeeper in pravega-operator (https://github.com/pravega/pravega-operator/pull/313). Now that bookkeeper installation was moved to separate repository/operator, we need the same changes.
Need to specify custom storage class for Bookkeeper volume.
Helm chart was modified to allow user to specify custom storage class.
Run installation with and without custom storage class. The change was tested.
=> Support for custom storage class for Bookkeeper volume

charts/bookkeeper/templates/_helpers.tpl, deploy/crds/crd.yaml, pkg/controller/bookkeepercluster/bookkeepercluster_controller.go, pkg/util/bookkeepercluster.go, pkg/util/zookeeper_util.go
*PRAVEGA_CLUSTER_NAME* is required to be set in order to delete znodes, but this value is not being correctly set.
Fixes #25 
It appends the value of *PRAVEGA_CLUSTER_NAME* to the name of the finalizer. This value is then read from the finalizer name at the time of deleting the znodes. 
It also populates the *DESIRED VERSION* field within the bookkeeper crd with the correct value.
Deletion of znodes should happen as expected after Bookkeeper Cluster deletion.
The following scenarios were tested :-
- Configmap is provided with the name of pravega cluster - In this case the pravega cluster name is appended to the finalizer name and the value is retrieved from this field at the time of zk metadata deletion
- The field `EnvVars` is empty - In …
=> Issue 25: Handling znode deletion

charts/app/bookkeeper-cluster.yaml, charts/app/crd.yaml, pkg/apis/bookkeeper/v1alpha1/status.go, pkg/controller/bookkeepercluster/bookkeepercluster_controller.go, pkg/util/k8sutil.go
This change enables the Bookkeeper Operator to emit a K8s Event for failure to cleanup BK metadata from zookeeper at the time of Bookkeeper cluster deletion.
Fixes #6 
The code creates an event and publishes it to the k8s event queue if there is a failure in cleaning up the metadata from the zookeeper nodes after deletion of the bookkeeper cluster.
An event should get added to kubernetes event queue, whenever zookeeper metadata fails to cleanup after bookkeeper cluster deletion.
The following is the describe output of the event that is created.
```
Name:             ZKMETA_CLEANUP_ERROR-nn6sd
Namespace:        default
Labels:           app=bookkeeper-cluster
bookkeeper_cluster=pravega-bk
Annotations:      <none>
API Version:      v1
Event …
```
=> Issue 6: Publish events for metadata cleanup failure

README.md, doc/manual-installation.md, pkg/util/k8sutil.go, pkg/util/zookeeper_util.go
The bookkeeper operator fails to delete metadata from zookeeper pods when the bookkeeper cluster is deployed in a non-default namespace.
Fixes #34 
It changes the zookeeper url as the operator is unable to resolve it when the svc is presrent in a different namespaces.
When the bookkeeper cluster which is deployed in a non-default namespace is deleted, the metadata from zookeeper will be successfully deleted which can be confirmed by finding the message `zookeeper metadata deleted` within the bookkeeper operator logs. 
The bookkeeper operator logs post bookkeepr cluster deletion will look like
```
time="2020-04-28T13:15:37Z" level=info msg="Reconciling BookkeeperCluster new/boo-pravega-bk\n"
time="2020-04-28T13:16:07Z" level=info …
```
=> Issue 34: Handling znode deletion in non-default namespace

go.mod, go.sum, pkg/controller/bookkeepercluster/bookie.go, pkg/controller/bookkeepercluster/bookie_test.go
Ledger and journal directories were hard coded in bookkeeper pod spec. Made changes to configure multiple journal/ledger directories if it is provided as part of `Options`
Fixes #41 
If journal/ledger directories are specified as part of Options that will be used as Mountpath. Otherwise default will be used
Tested by giving ledger/journal directories in bookkeeper spec options and with out giving the directory path
=> Issue 41: Add support for multiple Bookie ledger directories 

pkg/controller/bookkeepercluster/bookie.go
While creating the VolumeClaimTemplates for the Bookkeeper StatefulSet, the namespace of these PVCs is not explicitly set to that of the Bookkeeper Cluster.
Fixes #45 
Creates Bookkeeper VolumeClaimTemplates in the same namespace as the Bookkeeper Cluster
Created the bookkeeper cluster in the namespace `new`.
Verified that the PVC is created in the same namespace as the bookkeeper cluster
```
$ kubectl describe pvc index-pravega-bk-bookie-0 -n new
Name:          index-pravega-bk-bookie-0
Namespace:     new
StorageClass:  standard
Status:        Bound
Volume:        pvc-a4cf9134-469b-4650-9ea7-ef447c0787fd
Labels:        app=bookkeeper-cluster
bookkeeper_cluster=pravega-bk
component=bookie
Annotations:   pv.kubernetes.io/bind-completed: yes …
```
=> Issue 45: Create PVCs in cluster namespace

doc/bookkeeper-options.md, pkg/controller/bookkeepercluster/bookie.go, pkg/controller/bookkeepercluster/bookie_test.go
In operator code, we were setting env variable `BK_AUTORECOVERY` if the autorecovery is set and in default cases. But the env variable used in `bk_server.conf` file is `autoRecoveryDaemonEnabled`.  Changed the env variable name from `BK_AUTORECOVERY`  to `BK_autoRecoveryDaemonEnabled`
Fixes #12
Changed the env variable to `BK_autoRecoveryDaemonEnabled` and if autoRecovery is set to false in yaml file, update the env variable to false
Verified that `bk_server.conf` file is updated correctly based on the value set. Checked with bookeeper version `6.1` and `7.0`
=> Issue 12: BK_AUTORECOVERY environment variable set by the operator does not take effect

charts/bookkeeper-operator/templates/clusterrole.yaml, deploy/role.yaml
Due to lack of required clusterroles, bookkeeper upgrade was seen to fail when the bookeeper operator and bookkeeper cluster were deployed in different namespaces.
Fixes #54 
Adds the required clusterroles to the bookkeeper operator service account.
Bookkeeper Cluster is able to upgrade successfully even when the bookkeeper cluster and the bookkeeper operator are deployed in different namespaces.
=> Issue 54: Fixing Bookkeeper cluster upgrade failure

README.md, charts/bookkeeper/README.md, charts/bookkeeper/values.yaml, deploy/config_map.yaml, deploy/crds/cr.yaml, doc/manual-installation.md, doc/upgrade-cluster.md, example/cr-detailed.yaml, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types_test.go
Modifies the default name of the zookeeper client service from `zk-client:2181` to `zookeeper-client:2181`which is the default value created by zookeeper.
=> Changing default name of zookeeper service

charts/bookkeeper/README.md, charts/bookkeeper/values.yaml, pkg/controller/bookkeepercluster/bookie.go, pkg/controller/bookkeepercluster/bookie_test.go
After changes done by [this PR](https://github.com/pravega/bookkeeper-operator/pull/44), specifying LedgerDirectories for bookkeeper as a comma-separated list of directories `(ledgerDirectories: "/bk/ledgers/l0,/bk/ledgers/l1,/bk/ledgers/l2,/bk/ledgers/l3")`, creates following directory structure is inside the bookkeeper pods
```
$ ls /bk/ledgers/
l0  l0,  l1  l2  l3
$ ls /bk/ledgers/l0,/bk/ledgers/l1,/bk/ledgers/l2,/bk/ledgers/l3/
lost+found
```
Hence the ledger and journal directories are not getting mounted in the expected manner.
Fixes #59 
Splits the compound string provided to specify comma separated list of `ledgerDirectories` or `journalDirectories` and accordingly creates the mount paths.
After applying the fix, the comma separated …
=> Issue 59: Fixing Bookie failure

charts/bookkeeper-operator/README.md, charts/bookkeeper-operator/templates/operator.yaml, charts/bookkeeper-operator/templates/version_map.yaml, charts/bookkeeper-operator/values.yaml
The bookkeeper-operator should provide users a way to deploy a non-valid image version in non-production environments, since currently there doesn't seem to be any way to use the bookkeeper-operator charts (without modifying them) to deploy bookkeeper versions that are not already part of the version map.
Fixes #65 
When test-mode is enabled in the bookkeeper-operator, the major version that is provided by the user within `testmode.version` is added to the bk-supported-versions configmap that is created by the operator.
Provide the image version (major version number) that you wish to deploy which is not part of `version_map.yaml` by first enabling test-mode in the bookkeeper-operator `values.yaml` file in the following way
```
testmode: …
```
=> Issue 65: Allowing non-valid image versions to be used in non-production environments

charts/bookkeeper/README.md, charts/bookkeeper/templates/bookkeeper.yaml, charts/bookkeeper/values.yaml, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go, pkg/controller/bookkeepercluster/bookkeepercluster_controller.go, pkg/controller/bookkeepercluster/bookkeepercluster_controller_test.go
Addd a new field in spec `BlockOwnerDeletion`   If this filed is set to false, we are setting blockownerDeletion in Ownerreference to false for all the bookkeeper persistent volume claims.
Fixes #73 
Added a new field blockownerDeletion that can be configured by user. If it is set to false blockowner deletion is set to false for Persistent volume claims.
Verified that if block owner deletion is set to false , Pvcs are coming up fine in OPenshift environment
=> Issue 73: Provide support for configuring block owner deletion  for PVC's

charts/bookkeeper/templates/bookkeeper.yaml, deploy/crds/cr.yaml, doc/manual-installation.md, example/cr-detailed.yaml, pkg/controller/bookkeepercluster/upgrade.go
With the upgrade of controller runtime, the updated `client.List` method does not return the list of pods in a sorted order, which was breaking the sequential one-pod-at-a-time upgrade logic that had been implemented in the operator.
Fixes #82 
The list of pods returned by the `client.List` method is sorted by name before doing any further processing, to maintain consistency with the previous logic.
Upgrade the bookkeeper cluster from one version to another and ensure that not more than one pod is ugraded at any given time.
=> Issue 82: Handling Bookkeeper Upgrade

cmd/manager/main.go, go.mod, go.sum, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go, pkg/controller/bookkeepercluster/bookkeepercluster_controller.go, pkg/test/e2e/e2eutil/bkcluster_util.go, pkg/util/bookkeepercluster.go, pkg/util/bookkeepercluster_test.go, test/e2e/bookkeepercluster_test.go, test/e2e/cmchanges_test.go, test/e2e/upgrade_test.go
Signed-off-by: anishakj <anisha.kj@dell.com>
Added support to update bookkeeper spec and JVM options at run time
Fixes #86
If we make any changes to options or JVM options, config map is updated. And the bookkeeper pods will get restarted one by one. webhook validation is added  to prevent updating  ledger/journal/index directory path, 
Verified that updation is happening and pods are restarting if options or jvm options are updated
Verified with kubectl edit as well as helm upgrade
=> Added support for updating spec fields at run time

charts/bookkeeper/values.yaml, pkg/controller/bookkeepercluster/bookie.go
Provides user with the option to override the default the subpath name used by the operator while creating the ledger/journal/index directories. This is needed to allow operator upgrades from version 0.1.1 to 0.1.3 in the case where multiple ledger/journal/index directories have been specified with operator 0.1.1
Fixes #105 
In case the user specifies the ledgerSubPath and journalSubPath within the bookkeeper options, the operator will use this name suffixed with the appropriate index value as the subpath name to override the default subpath name used by the operator.
Specify the ledger and journal subpath within options in the following manner while upgrading from bookkeeper operator 0.1.1 to 0.1.3 when multiple journal and ledger …
=> Issue 105: Adding support for ledger/journal subpath modification

.github/workflows/ci.yaml, charts/bookkeeper-operator/templates/bookkeeper.pravega.io_bookkeeperclusters_crd.yaml, charts/bookkeeper/README.md, charts/bookkeeper/templates/bookkeeper.yaml, charts/bookkeeper/values.yaml, deploy/crds/bookkeeper.pravega.io_bookkeeperclusters_crd.yaml, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go, pkg/controller/bookkeepercluster/bookie.go, pkg/controller/bookkeepercluster/bookkeepercluster_controller.go, pkg/controller/bookkeepercluster/bookkeepercluster_controller_test.go
Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>
This pr helps prevent segmentstore and controller pods from evicting if number of bookkeeper pods are greater than number of nodes. By making the PDB Configurable.
Fixes #103 
Added **maxUnavailableBookkeeperReplicas** field which will be used to configure the Bookkeeper pdb.
Modify the above field and check inside the bookkeeper PDB's it should have the modified values.
=> Adding changes to modify bk configmap

pkg/controller/bookkeepercluster/bookkeepercluster_controller.go, pkg/controller/bookkeepercluster/bookkeepercluster_controller_test.go
… done at the same time
Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>
Added changes for Avoiding 2 Restarts when Both Version and cm changes are done at the same time. This makes the upgrade process fast and we don't get error messages due to race condition.
Fixes #109 
Code checks for any change in the version of the bk cluster when there are changes in cm and if there is change in the version
then we skip restart of pods and only upgrade the cm
Install bk cluster then upgrade the cluster along with changing some field in the option we should only see one restart of all k pods and the upgrade should complete.
=> Issue-109: Added changes for Avoiding 2 Restarts when Both Version and cm changes are done at the same time

charts/bookkeeper-operator/templates/pre-delete-hooks.yaml, charts/bookkeeper-operator/values.yaml
Provides a pre-delete hook which ensures that custom resources are deleted before deleting the operator.
Fixes #107 
Allows the operator to be deleted via helm only if the BookkeeperCluster custom resource has already been deleted, not otherwise.
- If you try to delete the bookkeeper operator before having deleted the BookkeeperCluster custom resource, the pre-delete job will fail, thereby not allowing the operator from being deleted.
- If you try to delete the bookkeeper operator after the BookkeeperCluster custom resource has been cleaned up successfully, the operator will also be successfully deleted.
=> Issue 107: Bookkeeper Operator pre-delete hook

charts/bookkeeper/values.yaml, pkg/controller/bookkeepercluster/bookie.go, pkg/controller/bookkeepercluster/bookie_test.go
- introduces the configMapVolumeMounts option as multiple key-value pairs, separated by commas and each consisting of a <configMapName>:<configKey>=<configFilePath> tuple.
- parses the configMapVolumeMounts values.
- adds the extracted values to the volumes list and containers' volumeMounts list.
Implements #83 
Bookkeeper operator should allow to specify "extra" configmap volumes to be mounted into bookie pods. Such config volumes may be used to import external configs for bookie use, such as log config.
The code implements the new bookkeeper option configMapVolumeMounts.
To use "extra" volumes in the bookkeeper pods, in the bookkeeper options, specify:
configMapVolumeMounts to add configMap volumes
The option consist of multiple key-value pairs, separated by commas and each consisting …
=> Issue 83: Add configmap volumeMount to bookie container

charts/bookkeeper/README.md, charts/bookkeeper/values.yaml, charts/bookkeeper/values/large.yaml, charts/bookkeeper/values/medium.yaml, charts/bookkeeper/values/minikube.yaml, charts/bookkeeper/values/small.yaml, pkg/controller/bookkeepercluster/bookie.go, pkg/controller/bookkeepercluster/bookie_test.go, pkg/test/e2e/e2eutil/bkcluster_util.go, test/e2e/cmchanges_test.go, test/e2e/multiple_bk_test.go
Removes the hardcoded JVM options from the operator code, so that users can easily set their desired configuration through the charts, and also modify them if required.
Fixes #129 
Removes the hardcoded JVM options from the operator code.
The bookkeeper cluster should be configured with the JVM options (i.e. memoryOpts, gcOpts, gcLoggingOpts, extraOpts) that are provided within the values.yaml by the user. Also these values can be easily modified even after the bookkeeper cluster has been deployed by editing the bookkeeper cluster configmap.
=> Issue 129: Making JVM options configurable

charts/bookkeeper-operator/templates/bookkeeper.pravega.io_bookkeeperclusters_crd.yaml, charts/bookkeeper/README.md, charts/bookkeeper/templates/bookkeeper.yaml, charts/bookkeeper/values.yaml, deploy/crds/bookkeeper.pravega.io_bookkeeperclusters_crd.yaml, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types_test.go, pkg/apis/bookkeeper/v1alpha1/zz_generated.deepcopy.go, pkg/controller/bookkeepercluster/bookie.go, pkg/controller/bookkeepercluster/bookie_test.go
add annoation field in bookkeeeper crd and attach annotation to bookie pods and sts
Fixes #131
add annoation field in bookkeeeper crd and attach annotation to bookie pods and sts
set bookie pods annoation via chart values and deploy bookkeeper with the built operator. kubectl describe bookie pods to see if the specified annotation is there.
=> Issue 131: add bookie pods annotation

charts/bookkeeper-operator/templates/bookkeeper.pravega.io_bookkeeperclusters_crd.yaml, charts/bookkeeper/README.md, charts/bookkeeper/templates/bookkeeper.yaml, charts/bookkeeper/values.yaml, deploy/crds/bookkeeper.pravega.io_bookkeeperclusters_crd.yaml, doc/configuration.md, doc/service-configuration.md, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go, pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types_test.go, pkg/controller/bookkeepercluster/bookie.go, pkg/controller/bookkeepercluster/bookie_test.go, pkg/test/e2e/e2eutil/bkcluster_util.go, pkg/util/bookkeepercluster.go, pkg/util/bookkeepercluster_test.go, test/e2e/basic_test.go
Currently headless svc name is hardcoded as `<clustername>-bookieheadless`. Made changes to support configuring service suffix,  so that larger cluster names can be given if required.
Fixes #132
Provide option to configure suffix of service names
All tests should pass
Verified able to configure headless svc suffix and if suffix is not mentioned it is taking default.
=> Issue 132: Shorten the service names generated by Bookkeeper Operator

Makefile, deploy/operator.yaml
Hardcodes the base version of the operator in the Makefile, which needs to be updated after every bookkeeper operator release, to serve as the base version.
Fixes #156 
Hardcodes the bookkeeper operator base version in the Makefile to compute the version for bookkeeper operator images that are build using `make build-image` command.
The final version for the bookkeeper operator is computed in the following format inside the Makefile
```
{base_version}-{number_of_commits_after_last_release}-{commit_id}
```
Running the command `make build-image` should build the bookkeeper-operator image with version in the desired format
=> Issue 156: Including operator base version in Makefile

test/e2e/resources/kubernetes_master_install.sh, test/e2e/resources/kubernetes_slave_install.sh
Signed-off-by: anishakj <anisha.kj@dell.com>
Updated scripts to use k8 version `1.21.2`
Fixes #164
Updated k8 version
All e2e should pass
=> Issue 164: Fix end to end tests for bookkeeper operator

pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go
Signed-off-by: Nishant Gupta <Nishant_Gupta3@dell.com>
Assigns the default values to the fields of index, journal and ledgers' volume claim templates in the bookkeeper pod which are not set by the user
Fixes #90
Currently the code sets the default value of the index, journal and ledger volume claim templates only if the entire volume claim templates is undefined and in case if the user does not provide few fields, it does not set them to default and throws an error. The fix to this was to check whether any of the fields is empty or not ("") and if it's true , then set them to the default values.
When deploying bookkeeper using charts , only provide values to certain fields of the `bookkeeper/values.yaml `**storage** object. Below are few scenarios to test with. In all the scenarios, if …
=> Issue 90: Bookkeeper pods do not come up if storage size for index/journal/ledger volume claim templates is not mentioned

pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go, test/e2e/cmchanges_test.go
Signed-off-by: SrishT <Srishti.Thakkar@emc.comT>
Disallows modification of the bookkeeper option `useHostNameAsBookieID` after the bookkeeper cluster has been deployed.
Fixes #169 
An additional validation check is added in the method `validateConfigMap` which ensures that the user cannot modify the value of `useHostNameAsBookieID` post deployment.
Trying to modify the value of the bookkeeper option useHostNameAsBookieID post deployment should result in the webhook throwing the following error
```
error: bookkeeperclusters.bookkeeper.pravega.io "bookkeeper" could not be patched: admission webhook "bookkeeperwebhook.pravega.io" denied the request: value of useHostNameAsBookieID should not be changed
```
=> Issue 169: Preventing modification of useHostNameAsBookieID post deployment

pkg/apis/bookkeeper/v1alpha1/bookkeepercluster_types.go
Signed-off-by: Andrey Andreev <andrey.andreev@dell.com>
The import of k8sutil is removed in bookkeepercluster_types.go and k8s.GetOperatorName() is replaced by the function GetOperatorName().
Closes #190 
Implements GetOperatorName() function that returns the value of OPERATOR_NAME env variable and/or error in case of empty or not set variable.
- bookkeepercluster_types.go and a corresponding package don't have dependency to k8sutil
- ZKMETA_CLEANUP_ERROR and UPGRADE_ERROR events should have the same operator name as before in ReportingController field
=> Issue 190: Remove k8sutil dependency in bookkeepercluster_types.go

cmd/manager/main.go, deploy/webhook.yaml
Signed-off-by: anishakj <anisha.kj@dell.com>
Update the default webhook port to `9443`
Fixes #194
Updated the port
All e2e should pass
=> Issue 194: Updating the default webhook port to 9443

.github/workflows/ci.yaml, controllers/upgrade.go, controllers/upgrade_test.go, test/e2e/resources/zookeeper_crd.yaml
Signed-off-by: anishakj <anisha.kj@dell.com>
Bookkeeper upgrade was failing to find the pods since the labels were not matching. Added a fix to use correct labels for listing
Fixes #202
While finding the pods with old version, labels selector was containing additional labels and pods were not listing. Upgrade was failing due to that
In order  to fix this we are using a subset of labels that will be present always. 
Added extra labels during upgrade and verified that upgrade is working as expected.
=> Issue 202: Fixing bookkeeper upgrade issue

api/v1alpha1/bookkeepercluster_types.go, config/crd/bases/bookkeeper.pravega.io_bookkeeperclusters.yaml, controllers/upgrade.go
Added a new field `upgradeTimeout` in CRD to configure the time
Fixes #209
Made changes to configure upgrade time
Verified bookkeeper upgrade by configuring upgrade time
=> Issue 209: Added fix to configure upgrade timeout

controllers/upgrade.go, controllers/upgrade_test.go
In some cases, after updating stateful set, `updatedReplicas` field in sts is not updating correctly. Due to this, the check 
```
if sts.Status.UpdatedReplicas == sts.Status.Replicas &&
sts.Status.UpdatedReplicas == sts.Status.ReadyReplicas 
```
is succeeding and make upgrade as completed. And pods are not coming up with new image
Fixes #213
Added additional check to ensure that all  the pods are updated with new version
Verified that upgrade is working
=> Issue 213: Upgrade of bookkeeper fails intermittently

Dockerfile
Signed-off-by: Nishant Gupta <Nishant_Gupta3@dell.com>
Upgrade busybox version to 1.35.0-r17 so as to fix [CVE-2022-30065](https://security.alpinelinux.org/vuln/CVE-2022-30065) and [CVE-2022-28391](https://security.alpinelinux.org/vuln/CVE-2022-28391)
Fixes #215
upgrades busybox version to 1.35.0-r17
- Pull the latest docker image
- Spawn a container out of that image and go inside the container
- run the command `apk list | grep busybox `to check the installed version of busybox
=> Updating busybox version to fix CVEs

controllers/bookkeepercluster_controller.go
Currently sts spec parameters are not updatable at runtime. Added support to restart sts pods, if any of the sts  fields are changed by editing  the bk cluster
Fixes #150
Added support to modify sts fields at runtime. If the fields are changed,  operator will initiate restart of pods
Verified by changing the fields. All the bookie pods are getting restarted one by one.
=> Issue 150: Fix for updating bookkeeper spec parameters

controllers/upgrade.go
Bookkeeper cluster upgrade is failing intermittently. In the case of failure, at the time of processing delete pod request pod is already deleted and is returning the error pod not found, which in turn sets the upgrade state to failed. Due to this reason subsequent pods are not getting updated
Fixes #120
In the case of deleting pod is failing due to `pod not found` dont return any error. so that upgrade of remaining pods can be performed without any issues
Performed bookkeeper upgrade multiple times and it was successful
=> Issue 120: bookkeeper cluster upgrade is failing intermittently

.github/workflows/ci.yaml
Bookkeeper operator end to end tests are failing after upgrading go version to `1.18`.
To fix this issue, we need to add git configuration before running e2e tests
Fixes #223
Added git configuration
Verified that e2e tests are passing
=> Issue 223: Fixing end to end tests for bookkeeper operator

controllers/upgrade.go, controllers/upgrade_test.go
In some cases, while updating bookkeeper pods, upgrade is failing with error Failed to get outdated pod . When this happens all the bk pods are already updated.
While upgradingbookie pods, even if the pods are updated with new version it takes some time to reflect in the status. So upgrade reconcile loop thinks upgrade is not completed and try to get an outdated pod. Since the pods are already updated, it fails to get outdated pod and makes upgrade as failed.
Fixes #220
Added an extra check not to update the pod if all the pods are updated to target version
Verified upgrade couple of times and is working fine
=> Issue 220: Bookkeeper cluster upgrade is failing intermittently

controllers/bookie.go, controllers/bookkeepercluster_controller.go, controllers/bookkeepercluster_controller_test.go
Changed the poddisruption budget version from `v1beta1` to `v1`
Fixes #228
To support k8 1.25, updated pod disruption budget
All end to end tests should pass
=> Issue 228: Update bookkeeper operator to support k8 1.25

controllers/upgrade.go
Fixing intermittent upgrade failure of bookkeeper.
Added some more conditions to handle error scenarios
Fixes #220
while during bookkeeper  update, it fails to get the pod sometimes. Issue is happening because while it tries to get an outdated pod, it has already updated. So added more checks to post error only if all pods were not updated
Peformed upgrade multiple time and issue is not seen
=> Issue 220: Fix for intermittent bookkeeper cluster upgrade failure
